# .github/workflows/build.yml
name: Build Debian Package and push to Repo server

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin
          java-package: jdk
          check-latest: false
      - name: Build DEB package
        run: ./gradlew :composeApp:packageDeb
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dhbw-next-${{ matrix.arch }}.deb
          path: composeApp/build/compose/binaries/main/deb/*.deb
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Deploy to APT server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*.deb"
          target: "/var/www/apt-repo/pool/main/"

      - name: Regenerate repository metadata
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REPO_HOST }}
          username: ${{ secrets.REPO_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/apt-repo
            dpkg-scanpackages --arch amd64 pool/ > dists/stable/main/binary-amd64/Packages
            gzip -9 -k dists/stable/main/binary-amd64/Packages
