# .github/workflows/build.yml
name: Build Multi-Arch Packages

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm64  # If available
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
      - name: Build DEB package
        run: ./gradlew :composeApp:packageDeb
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dhbw-next-${{ matrix.arch }}.deb
          path: composeApp/build/compose/binaries/main/deb/*.deb
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Deploy to APT server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*.deb"
          target: "/var/www/apt-repo/pool/main/"

      - name: Regenerate repository metadata
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REPO_HOST }}
          username: ${{ secrets.REPO_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/apt-repo
            dpkg-scanpackages --arch amd64 pool/ > dists/stable/main/binary-amd64/Packages
            dpkg-scanpackages --arch arm64 pool/ > dists/stable/main/binary-arm64/Packages
            gzip -9 -k dists/stable/main/binary-amd64/Packages
            gzip -9 -k dists/stable/main/binary-arm64/Packages
